### ISSUE TITLE
empty directories in the packages folder causes ci/cli to break.

### ISSUE THREAD

**Issue by NullVoxPopuli** [CrowdStrike/monorepo-next#79]
for example:

if there is:
```
packages/
 some-dir/
   # literally empty
```
the command:
`yarn start --tasks lint` will fail with the following error: 

```
Error: Cannot find module '$monorepoPath/packages/some-dir/package'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at firstPass ($monorepoPath/node_modules/monorepo-next/src/build-dep-graph.js:23:23)
    at buildDepGraph ($monorepoPath/node_modules/monorepo-next/src/build-dep-graph.js:102:3)
$monorepoPath/node_modules/@crowdstrike/package-release/src/utils/throw-up.js:4
process.on('unhandledRejection', up => { throw up; });
```

**Comment by kellyselden** [comment]
Turns out this is a duplicate #77
